### ISSUE TITLE
github registration/login redirection to localhost

### ISSUE THREAD

**Issue by shel3over** [01walid/dzlibs#3]
the github loging redirect to http://127.0.0.1:5000/callback?error=redirect_uri_mismatch

**Comment by 01walid** [comment]
You mean on the live website (dzlibs.io) ?
You're right anyway, cause I forgot to create another Github developer application  for the live website, the one it's using right now is just for testing, the callback url (on github) is still 127.0.0.1:5000. I'll create another dev app for the website that calls back correctly.
Thanks @shel3over :)

**Comment by shel3over** [comment]
@01walid if you separate the configuration file would be great 
i mean we can choose the configuration when we start the app :) to avoid exposing information on the repo

**Comment by 01walid** [comment]
I'm already -partially- doing this,
If you look at the config.py file you'll find DevelopmentConfig class and ProductionConfig class both inherit from a general purpose 'Config' class, the later one (that is still not yet developed) is supposed to take configs from either the environment variables or the "instance folder" introduced in Flask 0.8
see: http://flask.pocoo.org/docs/config/#instance-folders
and: http://flask.pocoo.org/docs/api/#configuration

the app.py file have this commented out on line 62 :) 
anyway, If you have better suggestions they're more than welcome :)
