### ISSUE TITLE
no module flask.ext.XXX

### ISSUE THREAD

**Issue by zirconias** [01walid/dzlibs#9]
i'm trying to get dzlibs up on my machine i got lot of  
no module flask.ext."XXX" module 

i fixed a part of it by entring to the tweeza folder and running pip install ../requirement.txt

i'm stuck  on "ImportError: No module named py3compat

**Comment by 01walid** [comment]
Don't forget the `-r`,  make sur the command is exactly:
`pip install -r requirements.txt` run it in the `dzlibs` folder
then, you first need to activate the virtual environment (if you created it)
`source venv/bin/activate`
you can now cd to `tweeza` folder, and run
`python manage.py runserver`

**Comment by zirconias** [comment]
i did it and still have random errors  ( after the py3compat module missed ) i have ImportError: No module named werkzeug.exceptions..

**Comment by 01walid** [comment]
Are you using python2 ? 
the project is not yet tested with python3, so make sure you're using python2
run `python --version`

**Comment by zirconias** [comment]
i followed readme , i'm on 2.7.5! weird!

**Comment by 01walid** [comment]
I think you either installed the modules system-wide, not in the virtualenv, or you're still not working in the virutal env, 
the command 
`source venv/bin/activate` has to be run **before** `pip install -r requirements.txt` so the packages will be installed there, in the new virtual environment.

else, try typing `deactivate`
then run `python manage.py runserver` maybe you installed the packages system-wide

**Comment by zirconias** [comment]
still get the ImportError: No module named py3compat
 and im running it on the venv, anyway i'll try a clean install tomorrow :nchalah:

**Comment by shel3over** [comment]
@zirconias  try to install it manually  using pip install py3compat

**Comment by zirconias** [comment]
won't work  for me,  i may hav  to take a look at flask and venv stuff to fix it..

could you test it on other ENV?
